name = "esl-review"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "esl-review"
database_id = "7184c3c6-7ebd-48d3-8358-932123e6c038"
